/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as KotRouteImport } from './routes/kot'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const KotRoute = KotRouteImport.update({
  id: '/kot',
  path: '/kot',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bills': typeof BillsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/kitchen': typeof KitchenRoute
  '/kot': typeof KotRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bills': typeof BillsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/kitchen': typeof KitchenRoute
  '/kot': typeof KotRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bills': typeof BillsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/kitchen': typeof KitchenRoute
  '/kot': typeof KotRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/bills'
    | '/categories'
    | '/dashboard'
    | '/items'
    | '/kitchen'
    | '/kot'
    | '/license'
    | '/login'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/bills'
    | '/categories'
    | '/dashboard'
    | '/items'
    | '/kitchen'
    | '/kot'
    | '/license'
    | '/login'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/bills'
    | '/categories'
    | '/dashboard'
    | '/items'
    | '/kitchen'
    | '/kot'
    | '/license'
    | '/login'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  BillsRoute: typeof BillsRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  ItemsRoute: typeof ItemsRoute
  KitchenRoute: typeof KitchenRoute
  KotRoute: typeof KotRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  PosRoute: typeof PosRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kot': {
      id: '/kot'
      path: '/kot'
      fullPath: '/kot'
      preLoaderRoute: typeof KotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  BillsRoute: BillsRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  ItemsRoute: ItemsRoute,
  KitchenRoute: KitchenRoute,
  KotRoute: KotRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  PosRoute: PosRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
